echo "Me ejecute 1!"
echo "Me ejecute 2!"
echo "Me ejecute 3!"
echo "Me ejecute 4!"
cd sss
echo "Me ejecute 5!"
echo "Me ejecute 6!"
echo "Me ejecute 7!"
echo "Me ejecute 8!"
echo "Me ejecute 9!"
echo "Me ejecute 10!"